/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeUIPanel.java
 *
 * Created on 07-05-2010, 19:55:35
 */
package UI;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import Dao.DepartmentDAO;
import Dao.EmployeeDAO;
import Dao.LocationDAO;
import Dao.ProjectDAO;
import Dao.RoleDAO;
import Entity.Department;
import Entity.Employee;
import Entity.Location;
import Entity.Project;
import Entity.Role;
import Util.ValidateFormTools;

public class PnlAdminEmployeeManage extends javax.swing.JPanel {

	private JLabel jLabel22;
	private JTextField tfAddRoleID;
	private JLabel jLabel24;
	private JTextField tfAddAdmin;
	private JLabel jLabel25;
	private JTextField tfAddDepartment;
	private JLabel jLabel26;
	private JTextField tfAddLocation;

	/** Creates new form EmployeeUIPanel */
	public PnlAdminEmployeeManage() {
		initComponents();
		loadDataToComboBox();

		String[] cols = new String[] { "ID", "Fullame", "Username", "Role", "Location", "Department", "Project",
				"Is Admin", "Transfers" };
		mdlTable = new DefaultTableModel(null, cols);
		tblData.setModel(mdlTable);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btnGroupAdmin = new javax.swing.ButtonGroup();
		tabbedPane = new javax.swing.JTabbedPane();
		tabViewEdit = new javax.swing.JPanel();
		pnlEditEmp = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		btnSave = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		tfEditPassword2 = new javax.swing.JPasswordField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		tfEditFullname = new javax.swing.JTextField();
		tfEditPassword1 = new javax.swing.JPasswordField();
		btnDelete = new javax.swing.JButton();
		tfEditLocationName = new javax.swing.JTextField();
		tfEditDepartmentName = new javax.swing.JTextField();
		tfEditProjectName = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		tfEditUsername = new javax.swing.JTextField();
		tfEditEmployeeID = new javax.swing.JTextField();
		jLabel23 = new javax.swing.JLabel();
		scrlpnlData = new javax.swing.JScrollPane();
		tblData = new org.jdesktop.swingx.JXTable();
		pnlSearchCondition = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		cboSearchLocation = new javax.swing.JComboBox();
		cboAddRole = new javax.swing.JComboBox();
		jLabel16 = new javax.swing.JLabel();
		cboSearchDepartment = new javax.swing.JComboBox();
		jLabel17 = new javax.swing.JLabel();
		cboSearchProject = new javax.swing.JComboBox();
		btnSearch = new javax.swing.JButton();
		jLabel19 = new javax.swing.JLabel();
		tfSearchFullname = new javax.swing.JTextField();
		tabAddNew = new javax.swing.JPanel();
		pnlAddEmp = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfAddFullname = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		cboAddLocation = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		cboAddDepartment = new javax.swing.JComboBox();
		cboIsAdmin = new javax.swing.JComboBox();
		btnAdd = new javax.swing.JButton();
		cboAddProject = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		tfAddPassword1 = new javax.swing.JPasswordField();
		jLabel7 = new javax.swing.JLabel();
		tfAddPassword2 = new javax.swing.JPasswordField();
		jLabel21 = new javax.swing.JLabel();
		tfAddUsername = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		tfAddRoleID = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		tfAddAdmin = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		tfAddDepartment = new javax.swing.JTextField();
		jLabel26 = new javax.swing.JLabel();
		tfAddLocation = new javax.swing.JTextField();

		setPreferredSize(new java.awt.Dimension(600, 600));
		setLayout(new java.awt.BorderLayout());

		tabbedPane.setMaximumSize(new java.awt.Dimension(791, 655));
		tabbedPane.setMinimumSize(new java.awt.Dimension(791, 655));
		tabbedPane.setPreferredSize(new java.awt.Dimension(791, 655));

		tabViewEdit.setPreferredSize(new java.awt.Dimension(300, 600));
		tabViewEdit.setLayout(new java.awt.BorderLayout());

		pnlEditEmp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Calibri", 1, 12))); // NOI18N
		pnlEditEmp.setPreferredSize(new java.awt.Dimension(170, 175));
		pnlEditEmp.setRequestFocusEnabled(false);

		jLabel13.setText("Project:");

		btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save.png"))); // NOI18N
		btnSave.setText("Save");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		jLabel10.setText("Confim Pasword:");

		jLabel11.setText("Location:");

		jLabel12.setText("Department:");

		tfEditPassword2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfEditPassword2ActionPerformed(evt);
			}
		});

		jLabel8.setText("Fullname:");

		jLabel9.setText("Password:");

		btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png"))); // NOI18N
		btnDelete.setText("Delete");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		tfEditLocationName.setEditable(false);
		tfEditLocationName.setEnabled(false);

		tfEditDepartmentName.setEditable(false);
		tfEditDepartmentName.setEnabled(false);

		tfEditProjectName.setEditable(false);
		tfEditProjectName.setEnabled(false);

		jLabel20.setText("Username:");

		tfEditUsername.setEditable(false);
		tfEditUsername.setEnabled(false);

		tfEditEmployeeID.setEditable(false);
		tfEditEmployeeID.setEnabled(false);

		jLabel23.setText("Employee ID:");
		jLabel22.setText("Role ID:");
		jLabel24.setText("Is Admin?:");
		jLabel25.setText("Department ID: ");
		jLabel26.setText("Location ID: ");

		javax.swing.GroupLayout pnlEditEmpLayout = new javax.swing.GroupLayout(pnlEditEmp);
		pnlEditEmp.setLayout(pnlEditEmpLayout);
		pnlEditEmpLayout
				.setHorizontalGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlEditEmpLayout.createSequentialGroup().addContainerGap().addGroup(pnlEditEmpLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										pnlEditEmpLayout.createSequentialGroup().addGap(252, 252, 252)
												.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(
														tfEditLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel13,
														javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(tfEditProjectName, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlEditEmpLayout.createSequentialGroup().addGroup(pnlEditEmpLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlEditEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(pnlEditEmpLayout.createSequentialGroup()
														.addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(tfEditUsername,
																javax.swing.GroupLayout.PREFERRED_SIZE, 150,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(pnlEditEmpLayout.createSequentialGroup()
														.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(tfEditPassword1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 150,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(pnlEditEmpLayout.createSequentialGroup()
												.addGroup(pnlEditEmpLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(pnlEditEmpLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(tfEditEmployeeID,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(tfEditFullname,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 150,
																Short.MAX_VALUE))
												.addGap(18, 18, 18)
												.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(tfEditDepartmentName,
														javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(102, 102, 102)
										.addGroup(pnlEditEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(pnlEditEmpLayout.createSequentialGroup()
										.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfEditPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(19349, Short.MAX_VALUE)));
		pnlEditEmpLayout.setVerticalGroup(pnlEditEmpLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlEditEmpLayout.createSequentialGroup().addGroup(pnlEditEmpLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(tfEditProjectName, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel11)
								.addComponent(tfEditLocationName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel13)
								.addComponent(tfEditEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel23)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12)
								.addComponent(tfEditDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfEditFullname, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnSave)
								.addComponent(tfEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel20))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDelete).addComponent(jLabel9).addComponent(tfEditPassword1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlEditEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(tfEditPassword2,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(43, 43, 43)));

		tabViewEdit.add(pnlEditEmp, java.awt.BorderLayout.SOUTH);

		scrlpnlData.setPreferredSize(new java.awt.Dimension(300, 350));
		scrlpnlData.setRequestFocusEnabled(false);

		tblData.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		tblData.setEditable(false);
		tblData.setSortable(false);
		tblData.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tblDataMouseClicked(evt);
			}
		});
		tblData.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				tblDataKeyReleased(evt);
			}
		});
		scrlpnlData.setViewportView(tblData);

		tabViewEdit.add(scrlpnlData, java.awt.BorderLayout.CENTER);

		pnlSearchCondition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Calibri", 1, 12))); // NOI18N
		pnlSearchCondition.setMaximumSize(null);
		pnlSearchCondition.setPreferredSize(new java.awt.Dimension(100, 130));

		jLabel15.setText("Location:");

		cboSearchLocation.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel16.setText("Department:");

		cboSearchDepartment.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		cboSearchDepartment.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cboSearchDepartmentActionPerformed(evt);
			}
		});

		jLabel17.setText("Project:");

		cboSearchProject.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_search.png"))); // NOI18N
		btnSearch.setText("Search");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		jLabel19.setText("Fullname:");

		javax.swing.GroupLayout pnlSearchConditionLayout = new javax.swing.GroupLayout(pnlSearchCondition);
		pnlSearchCondition.setLayout(pnlSearchConditionLayout);
		pnlSearchConditionLayout.setHorizontalGroup(pnlSearchConditionLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlSearchConditionLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlSearchConditionLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlSearchConditionLayout.createSequentialGroup()
										.addGroup(pnlSearchConditionLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(pnlSearchConditionLayout.createSequentialGroup()
														.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(cboSearchDepartment,
																javax.swing.GroupLayout.PREFERRED_SIZE, 150,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(pnlSearchConditionLayout.createSequentialGroup()
														.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(cboSearchLocation,
																javax.swing.GroupLayout.PREFERRED_SIZE, 150,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(34, 34, 34).addComponent(jLabel17,
												javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlSearchConditionLayout.createSequentialGroup()
										.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfSearchFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(cboSearchProject, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(19444, Short.MAX_VALUE)));
		pnlSearchConditionLayout.setVerticalGroup(
				pnlSearchConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlSearchConditionLayout.createSequentialGroup().addGap(11, 11, 11)
								.addGroup(pnlSearchConditionLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlSearchConditionLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel17)
												.addComponent(cboSearchProject, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnSearch).addComponent(jLabel15)
												.addComponent(cboSearchLocation))
										.addGroup(pnlSearchConditionLayout.createSequentialGroup().addGap(31, 31, 31)
												.addGroup(pnlSearchConditionLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel16).addComponent(cboSearchDepartment,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(pnlSearchConditionLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel19).addComponent(tfSearchFullname,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(29, Short.MAX_VALUE)));

		tabViewEdit.add(pnlSearchCondition, java.awt.BorderLayout.NORTH);

		tabbedPane.addTab("Employee", new javax.swing.ImageIcon(getClass().getResource("/images/table.png")),
				tabViewEdit); // NOI18N

		tabAddNew.setPreferredSize(new java.awt.Dimension(350, 330));
		tabAddNew.setLayout(new java.awt.BorderLayout());

		pnlAddEmp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Calibri", 1, 12))); // NOI18N
		pnlAddEmp.setPreferredSize(new java.awt.Dimension(150, 250));
		pnlAddEmp.setRequestFocusEnabled(false);

		jLabel1.setText("Fullname:");

		jLabel2.setText("Location:");

		cboAddLocation.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		cboAddLocation.setMaximumSize(null);

		cboIsAdmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True", "False" }));
		cboIsAdmin.setMaximumSize(null);

		jLabel3.setText("Department:");

		jLabel4.setText("Password:");

		cboAddDepartment.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		cboAddDepartment.setMaximumSize(null);

		cboAddRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
		cboAddRole.setMaximumSize(null);

		btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_add.png"))); // NOI18N
		btnAdd.setText("Add");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		cboAddProject.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Phát triển giống cây trồng và nguồn lợi thuỷ sản", "Item 3", "Item 4" }));
		cboAddProject.setMaximumSize(null);
		cboAddProject.setMinimumSize(new java.awt.Dimension(56, 18));

		jLabel5.setText("Project");

		jLabel7.setText("Confirm Passord:");

		jLabel21.setText("User name:");

		javax.swing.GroupLayout pnlAddEmpLayout = new javax.swing.GroupLayout(pnlAddEmp);
		pnlAddEmp.setLayout(pnlAddEmpLayout);
		pnlAddEmpLayout.setHorizontalGroup(pnlAddEmpLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlAddEmpLayout.createSequentialGroup().addContainerGap().addGroup(pnlAddEmpLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlAddEmpLayout.createSequentialGroup().addGroup(pnlAddEmpLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddEmpLayout
										.createSequentialGroup()
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfAddFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddEmpLayout
										.createSequentialGroup()
										.addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlAddEmpLayout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(cboAddLocation, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(cboAddProject, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pnlAddEmpLayout.createSequentialGroup()
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(cboAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE)

										)))
						.addGroup(pnlAddEmpLayout.createSequentialGroup().addGroup(pnlAddEmpLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup().addComponent(jLabel7)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(tfAddPassword2))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup().addComponent(jLabel22)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(cboAddRole))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup().addComponent(jLabel24)
//												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//												.addComponent(tfAddAdmin)
												.addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
//												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(cboIsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup()
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(tfAddPassword1, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354,
										Short.MAX_VALUE)
								.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(19349, Short.MAX_VALUE)));
		pnlAddEmpLayout.setVerticalGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlAddEmpLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup().addGroup(pnlAddEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(cboAddLocation, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5).addComponent(cboAddProject,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(pnlAddEmpLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3).addComponent(cboAddDepartment,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										pnlAddEmpLayout.createSequentialGroup()
												.addGroup(pnlAddEmpLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1).addComponent(
																tfAddFullname, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(pnlAddEmpLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel21).addComponent(tfAddUsername,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlAddEmpLayout.createSequentialGroup()
										.addGroup(pnlAddEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4).addComponent(tfAddPassword1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(pnlAddEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel7).addComponent(tfAddPassword2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(pnlAddEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel22)
												.addComponent(cboAddRole, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)

												.addComponent(tfAddPassword2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(pnlAddEmpLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel24).addComponent(cboIsAdmin,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

//										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

								)

								.addComponent(btnAdd))
						.addGap(123, 123, 123)));

		tabAddNew.add(pnlAddEmp, java.awt.BorderLayout.NORTH);

		tabbedPane.addTab("Add Employee", new javax.swing.ImageIcon(getClass().getResource("/images/contact-new.png")),
				tabAddNew); // NOI18N

		add(tabbedPane, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
		if (validateAddNew()) {
//			String rawPass = new String(tfAddPassword1.getPassword());
//			Employee empObj = new Employee();
//			empObj.setEmployeeName(tfAddFullname.getText());
//
//			empObj.setUsername(tfAddUsername.getText());
//
//			/* get Id respective cbo */
//			int locationID = locationLst.get(cboAddLocation.getSelectedIndex()).getLocationID();
//			int departmentID = departmentLst.get(cboAddDepartment.getSelectedIndex()).getDepartmentID();
//			int projectID = projectLst.get(cboAddProject.getSelectedIndex()).getProjectID();
//
//			empObj.getLocation().setLocationID(locationID);
//			empObj.getDepartment().setDepartmentID(departmentID);
//			empObj.getProject().setProjectID(projectID);

			String rawPass = new String(tfAddPassword1.getPassword());
//			Employee empObj = new Employee();
//			empObj.setEmployeeName(txtFullName.getText());

//			empObj.setUsername(txtUserName.getText());

			/* get Id respective cbo */
			int locationID = locationLst.get(cboAddLocation.getSelectedIndex()).getLocationID();
			int departmentID = departmentLst.get(cboAddDepartment.getSelectedIndex()).getDepartmentID();
			int projectID = projectLst.get(cboAddProject.getSelectedIndex()).getProjectID();

			int roleID = roleLst.get(cboAddRole.getSelectedIndex()).getRoleID();
			boolean isAdmin = cboIsAdmin.getSelectedItem().toString() == "True" ? true : false;
			Role role = new Role(roleID);
			Project project = new Project(projectID);
			Department department = new Department(departmentID);
			Location location = new Location(locationID);
//
			Employee empObj = new Employee(tfAddFullname.getText(), rawPass, role, isAdmin, project, department,
					location);

			JOptionPane.showMessageDialog(null, "Data Insert Successfully");
			clearTextField();
			try {
				EmployeeDAO.insertEmployee(empObj);
			} catch (ClassNotFoundException ex) {
				JOptionPane.showMessageDialog(null, "Cannot insert into Database", "Add New Error",
						JOptionPane.ERROR_MESSAGE);
				Logger.getLogger(PnlAdminEmployeeManage.class.getName()).log(Level.SEVERE, null, ex);
			} catch (SQLException ex) {
				JOptionPane.showMessageDialog(null, "Cannot insert into Database", "Add New Error",
						JOptionPane.ERROR_MESSAGE);
				Logger.getLogger(PnlAdminEmployeeManage.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}// GEN-LAST:event_btnAddActionPerformed

	private void clearTextField() {
		tfAddFullname.setText("");
		tfAddPassword1.setText("");
		tfAddPassword2.setText("");
		tfAddUsername.setText("");
		tfAddRoleID.setText("");
		cboIsAdmin.setSelectedItem("None");
	}

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed
		loadData();
	}// GEN-LAST:event_btnSearchActionPerformed

	private void tblDataKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tblDataKeyReleased
		if (tblData.getSelectedRow() != -1) {
			loadEditData();
		}
	}// GEN-LAST:event_tblDataKeyReleased

	private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblDataMouseClicked
		if (tblData.getSelectedRow() != -1) {
			loadEditData();
		}
	}// GEN-LAST:event_tblDataMouseClicked

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		if (tfEditEmployeeID.getText().compareTo("") != 0) {
			if (validateEdit()) {
				try {
					Employee emp = EmployeeDAO.selectOneEmployeeByID(Integer.parseInt(tfEditEmployeeID.getText()));
					emp.setEmployeeName(tfEditFullname.getText());
					String rawPass = String.valueOf(tfEditPassword1.getPassword());
					EmployeeDAO.updateEmployee(emp);

					clearEditData();
					loadData();

					JOptionPane.showMessageDialog(null, "Update data Successfully", "Update Successfully",
							JOptionPane.INFORMATION_MESSAGE);

				} catch (ClassNotFoundException ex) {
					JOptionPane.showMessageDialog(null, "Oops ! Cannot update to Database", "Update Error",
							JOptionPane.ERROR_MESSAGE);
				} catch (SQLException ex) {
					ex.printStackTrace();
					JOptionPane.showMessageDialog(null, "Oops ! Cannot update to Database", "Update Error",
							JOptionPane.ERROR_MESSAGE);
				}

			}
		} else {
			JOptionPane.showMessageDialog(this, "You have to select a row in the table below.", "No Row Selected",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}// GEN-LAST:event_btnSaveActionPerformed

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
		if (tblData.getSelectedRow() != -1) {
			if (validateDelete()) {

				if (JOptionPane.showConfirmDialog(null, "Do you really want to delete this Employee ?",
						"Delete Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
					try {

						EmployeeDAO.deleteEmployee(Integer.parseInt(tfEditEmployeeID.getText()));
						JOptionPane.showMessageDialog(null, "Delete Successfully");
						loadData();
						clearEditData();
					} catch (SQLException ex) {
						JOptionPane.showMessageDialog(null, "Delete Failed !", "Opps ! Delete Error",
								JOptionPane.ERROR_MESSAGE);
						ex.printStackTrace();
					} catch (ClassNotFoundException ex) {
						JOptionPane.showMessageDialog(null, "Delete Failed !", "Opps ! Delete Error",
								JOptionPane.ERROR_MESSAGE);
						ex.printStackTrace();
					}

				}

			}
		}
	}// GEN-LAST:event_btnDeleteActionPerformed

	private void cboSearchDepartmentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboSearchDepartmentActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cboSearchDepartmentActionPerformed

	private void tfEditPassword2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfEditPassword2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfEditPassword2ActionPerformed

	private void loadEditData()// Load Data from table, when user click to chose a row on Table
	{
		int index = tblData.getSelectedRow();
		Employee empTmp = empLst.get(index);

		tfEditEmployeeID.setText(String.valueOf(empTmp.getEmployeeID()));
		tfEditFullname.setText(empTmp.getEmployeeName());
		tfEditLocationName.setText(empTmp.getLocation().getLocationName());
		tfEditProjectName.setText(empTmp.getProject().getProjectName());
		tfEditDepartmentName.setText(empTmp.getDepartment().getDepartmentName());

		tfEditUsername.setText(empTmp.getUsername());

	}

	private void loadData()// Load data from DB to Table, use ConditionString base on Filter
	{
		/* get Employee by condition String */
		try {
			/* Get from database */
			empLst = null;
			empLst = EmployeeDAO.selectAllEmployeeByCondition(makeConditionString());

			String[] cols = new String[] { "ID", "Fullame", "Role", "Location", "Department", "Project", "Is Admin",
					"Transfers" };
			mdlTable = new DefaultTableModel(null, cols);
			for (Employee emp : empLst) {
				Vector row = new Vector();
				row.add(emp.getEmployeeID());
				row.add(emp.getEmployeeName());
//				row.add(emp.getUsername());
				row.add(emp.getRole().getRoleName());
				row.add(emp.getLocation().getLocationName());
				row.add(emp.getDepartment().getDepartmentName());
				row.add(emp.getProject().getProjectName());
				if (emp.isSystemAdmin()) {
					row.add("Yes");
				} else {
					row.add("No");
				}
				row.add(emp.getNumberOfTransfer());
				mdlTable.addRow(row);
			}
			tblData.setModel(mdlTable);

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(DialogSelectEmployee.class.getName()).log(Level.SEVERE, null, ex);
		} catch (SQLException ex) {
			Logger.getLogger(DialogSelectEmployee.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private String makeConditionString()// make SQL condition String from Filter to select Data from DB
	{
		StringBuilder condition = new StringBuilder();
		condition.append(" 1=1 ");/* append this to add AND clause later */
		int dept = cboSearchDepartment.getSelectedIndex() - 1;
		int location = cboSearchLocation.getSelectedIndex() - 1;
		int project = cboSearchProject.getSelectedIndex() - 1;

		/* Make condition String from ComboBox */
		if (dept >= 0) {
			condition.append(" AND Employees.DepartmentID = ");
			condition.append(departmentLst.get(dept).getDepartmentID());
		}
		if (location >= 0) {
			condition.append(" AND Employees.LocationID = ");
			condition.append(locationLst.get(location).getLocationID());
		}
		if (project >= 0) {
			condition.append(" AND Employees.ProjectID = ");
			condition.append(projectLst.get(project).getProjectID());
		}

		/* Make condion Fullname input */
		String empName = tfSearchFullname.getText().trim();
		if (empName.compareTo("") != 0) {
			while (empName.contains("  ")) {
				empName = empName.replace("  ", " ");
			} // Normalize input String
			empName = empName.replace(" ", "%' OR Employees.EmployeeName LIKE N'%");// add Like Clause

			StringBuilder empNameCond = new StringBuilder();
			empNameCond.append(" AND (Employees.EmployeeName LIKE N'%");
			empNameCond.append(empName);
			empNameCond.append("%' )");
			condition.append(empNameCond.toString());
		}

		// System.out.println(condition.toString());

		return condition.toString();
	}

	private boolean validateAddNew()// Validate the add new Employee Form
	{
		String msg = "";
		/* Check DepartmentName not = "" */
		if (!ValidateFormTools.isFilledTextField(tfAddFullname, true))// trim the text in tfAddDepartmentName , check
																		// blank
		{
			msg += "\n- Employee Fullname cannot be blank.";
		}
		tfAddFullname.setText(tfAddFullname.getText().trim());

		/* Check Username blank or not */
		if (!ValidateFormTools.isFilledTextField(tfAddUsername, true))// trim the text in tfAddDepartmentName , check
																		// blank
		{
			msg += "\n- Employee username cannot be blank.";
		}
		tfAddUsername.setText(tfAddUsername.getText().trim());

		/* Check Username is not containing space */
		if (tfAddUsername.getText().contains(" ")) {
			msg += "\n- Employee username cannot contains space.";
		}
		String username = tfAddUsername.getText();
		while (username.contains(" ")) {
			username = username.replace(" ", "");
		}
		tfAddUsername.setText(username);

		/* Check Username is avaiable in DB */
		try {
			if (!EmployeeDAO.isAvaiableUsername(tfAddUsername.getText())) {
				msg += "\n- Employee username cannot be use because it's not avaiable. Please select another one.";
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(PnlAdminEmployeeManage.class.getName()).log(Level.SEVERE, null, ex);
		} catch (SQLException ex) {
			Logger.getLogger(PnlAdminEmployeeManage.class.getName()).log(Level.SEVERE, null, ex);
		}

		/* Check Password not blank */
		if (String.valueOf(tfAddPassword1.getPassword()).compareTo("") == 0) {
			msg += "\n- Password cannot be blank";
		}

		/* Check Repeat Password not blank */
		if (!ValidateFormTools.isSamePassword(tfAddPassword1, tfAddPassword2)) {
			msg += "\n- Repeat password not correct";
		}

		if (msg.compareTo("") != 0) {
			JOptionPane.showMessageDialog(null, "Oops ! There are some error" + msg, "Add New Error",
					JOptionPane.ERROR_MESSAGE);
			return false;
		} else {
			return true;
		}
	}

	private boolean validateEdit()// Validate the edit Employee Form
	{
		String msg = "";
		/* Check DepartmentName not = "" */
		if (!ValidateFormTools.isFilledTextField(tfEditFullname, true))// trim the text in tfEditDepartmentName , check
																		// blank
		{
			msg += "\n- New Employee Fullname cannot be blank.";
		}
		tfEditFullname.setText(tfEditFullname.getText().trim());

		/* Check Password not blank */
		if (String.valueOf(tfEditPassword1.getPassword()).compareTo("") == 0) {
			msg += "\n- Password cannot be blank";
		}

		/* Check Repeat Password not blank */
		if (!ValidateFormTools.isSamePassword(tfEditPassword1, tfEditPassword2)) {
			msg += "\n- Repeat password not correct";
		}

		if (msg.compareTo("") != 0) {
			JOptionPane.showMessageDialog(null, "Oops ! There are some error" + msg, "Update Error",
					JOptionPane.ERROR_MESSAGE);
			return false;
		} else {
			return true;
		}
	}

	private void clearEditData() {
		tfEditDepartmentName.setText("");
		tfEditEmployeeID.setText("");
		tfEditFullname.setText("");
		tfEditLocationName.setText("");
		tfEditPassword1.setText("");
		tfEditPassword2.setText("");
		tfEditProjectName.setText("");
		tfEditUsername.setText("");
	}

	private boolean validateDelete() {
		int rowI = tblData.getSelectedRow();
		int trans = empLst.get(rowI).getNumberOfTransfer();
		if (trans != 0) {
			JOptionPane.showMessageDialog(null,
					"Oops ! You cannot delete this employee because there are some transfer are belong to this employee.",
					"Delete Error", JOptionPane.ERROR_MESSAGE);
			return false;
		}
		return true;
	}

	/* Load Data From DB and add to combo boxes */
	private void loadDataToComboBox() {
		try {
			/* Load Locations */
			locationLst = LocationDAO.selectAllLocation();
			cboAddLocation.removeAllItems();
			cboSearchLocation.removeAllItems();

			cboSearchLocation.addItem("All Location");
			for (Location location : locationLst) {
				cboAddLocation.addItem(location.getLocationName());
				cboSearchLocation.addItem(location.getLocationName());
			}

			roleLst = RoleDAO.selectAllRole();
			cboAddRole.removeAllItems();
			for (Role role : roleLst) {
				cboAddRole.addItem(role.getRoleName());
//				cboAddRole.addItem(location.getLocationName());
			}

			/* Load Department */
			departmentLst = DepartmentDAO.selectAllDepartment();
			cboAddDepartment.removeAllItems();

			cboSearchDepartment.removeAllItems();
			cboSearchDepartment.addItem("All Department");
			for (Department dept : departmentLst) {
				cboAddDepartment.addItem(dept.getDepartmentName());
				cboSearchDepartment.addItem(dept.getDepartmentName());
			}

			/* Load Projects */
			projectLst = ProjectDAO.selectAllProject();
			cboAddProject.removeAllItems();
			cboSearchProject.removeAllItems();
			cboSearchProject.addItem("All Project");
			for (Project proj : projectLst) {
				cboAddProject.addItem(proj.getProjectName());
				cboSearchProject.addItem(proj.getProjectName());
			}

		} catch (SQLException ex) {
			Logger.getLogger(DialogSelectEmployee.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(DialogSelectEmployee.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	List<Location> locationLst;
	List<Department> departmentLst;
	List<Project> projectLst;
	List<Role> roleLst;
	List<Employee> empLst;
	DefaultTableModel mdlTable;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDelete;
	private javax.swing.ButtonGroup btnGroupAdmin;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnSearch;
	private javax.swing.JComboBox cboAddDepartment;
	private javax.swing.JComboBox cboAddRole;
	private javax.swing.JComboBox cboAddLocation;
	private javax.swing.JComboBox cboAddProject;
	private javax.swing.JComboBox cboSearchDepartment;
	private javax.swing.JComboBox cboSearchLocation;
	private javax.swing.JComboBox cboSearchProject;
	private javax.swing.JComboBox cboIsAdmin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel pnlAddEmp;
	private javax.swing.JPanel pnlEditEmp;
	private javax.swing.JPanel pnlSearchCondition;
	private javax.swing.JScrollPane scrlpnlData;
	private javax.swing.JPanel tabAddNew;
	private javax.swing.JPanel tabViewEdit;
	private javax.swing.JTabbedPane tabbedPane;
	private org.jdesktop.swingx.JXTable tblData;
	private javax.swing.JTextField tfAddFullname;
	private javax.swing.JPasswordField tfAddPassword1;
	private javax.swing.JPasswordField tfAddPassword2;
	private javax.swing.JTextField tfAddUsername;
	private javax.swing.JTextField tfEditDepartmentName;
	private javax.swing.JTextField tfEditEmployeeID;
	private javax.swing.JTextField tfEditFullname;
	private javax.swing.JTextField tfEditLocationName;
	private javax.swing.JPasswordField tfEditPassword1;
	private javax.swing.JPasswordField tfEditPassword2;
	private javax.swing.JTextField tfEditProjectName;
	private javax.swing.JTextField tfEditUsername;
	private javax.swing.JTextField tfSearchFullname;
	// End of variables declaration//GEN-END:variables
}
