package UI;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Dao.LocationDAO;
import Entity.Location;

public class PnlUserLocationList extends javax.swing.JPanel {

	/** Tạo form LocationEmployeeUIPanel */
	public PnlUserLocationList() {
		initComponents();

		loadTableData();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		spnlLocationData = new javax.swing.JScrollPane();
		spnlLocationData1 = new javax.swing.JScrollPane();
		tblData = new org.jdesktop.swingx.JXTable();

		tblData.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		spnlLocationData1.setViewportView(tblData);

		spnlLocationData.setViewportView(spnlLocationData1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(spnlLocationData, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(spnlLocationData, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
						.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void loadTableData() {
		try {
			List<Location> locationList = LocationDAO.selectAllLocation();
			tblModel.addColumn("Mã Địa chỉ");
			tblModel.addColumn("Tên Địa chỉ");
			tblModel.addColumn("Số nhân viên");
			for (Location location : locationList) {
				Vector<String> row = new Vector<String>();
				row.addElement(String.valueOf(location.getLocationID()));
				row.addElement(location.getLocationName());
				row.addElement(String.valueOf(location.getNumberOfEmployees()));
				tblModel.addRow(row);
			}
			tblData.setModel(tblModel);
		} catch (ClassNotFoundException ex) {
			JOptionPane.showMessageDialog(null, "Không thể load từ CSDL", "Lỗi", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Không thể load từ CSDL", "Lỗi", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane spnlLocationData;
	private javax.swing.JScrollPane spnlLocationData1;
	private org.jdesktop.swingx.JXTable tblData;
	// End of variables declaration//GEN-END:variables
	DefaultTableModel tblModel = new DefaultTableModel();
}
