/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoleEmployeeUIPanel.java
 *
 
 */
package UI;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Dao.DepartmentDAO;
import Entity.Department;

public class PnlUserDepartmentList extends javax.swing.JPanel {

	/** Tạo form RoleEmployeeUIPanel */
	public PnlUserDepartmentList() {
		initComponents();

		loadTableData();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void loadTableData() {
		try {
			List<Department> departmentList = DepartmentDAO.selectAllDepartment();
			tblModel.addColumn("Mã phòng ban");
			tblModel.addColumn("Tên phòng ban");
			tblModel.addColumn("Số nhân viên");
			for (Department department : departmentList) {
				Vector<String> row = new Vector<String>();
				row.addElement(String.valueOf(department.getDepartmentID()));
				row.addElement(department.getDepartmentName());
				row.addElement(String.valueOf(department.getNumOfEmployee()));
				tblModel.addRow(row);
			}
			tblData.setModel(tblModel);
		} catch (ClassNotFoundException ex) {
			JOptionPane.showMessageDialog(null, "Không thể load từ CSDL", "Lỗi", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Không thể load từ CSDL", "Lỗi", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}

	}

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		spnlRoleData = new javax.swing.JScrollPane();
		spnlRoleData1 = new javax.swing.JScrollPane();
		tblData = new org.jdesktop.swingx.JXTable();

		setPreferredSize(new java.awt.Dimension(600, 600));

		tblData.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		spnlRoleData1.setViewportView(tblData);

		spnlRoleData.setViewportView(spnlRoleData1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(spnlRoleData, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(spnlRoleData, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
						.addContainerGap()));

		getAccessibleContext().setAccessibleName("List Role");
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JScrollPane spnlRoleData;
	private javax.swing.JScrollPane spnlRoleData1;
	private org.jdesktop.swingx.JXTable tblData;
	// End of variables declaration//GEN-END:variables
	DefaultTableModel tblModel = new DefaultTableModel();
}
